UNIQUE_KNOWLEDGE_BD/UNIQUE_KNOWLEDGE_BD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UNIQUE_KNOWLEDGE_BD/core/urls.py
from django import views
from django.urls import path, include
from core.views import (create_checkout_session, save_checkout_info, add_to_cart, add_to_wishlist, ajax_add_review,
                        ajax_contact_form, cart_view, category_list_view, category_product_list__view, checkout,
                        customer_dashboard, delete_item_from_cart, filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, product_detail_view, product_list_view, remove_wishlist, search_view, tag_list, update_cart, vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, purchase_guide, privacy_policy, terms_of_service)

app_name = "core"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list__view, name="category-product-list"),
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),
    path("save_checkout_info/", save_checkout_info, name="save_checkout_info"),
    path("checkout/<oid>/", checkout, name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-address/", make_address_default, name="make-default-address"),
    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),
    path("about_us/", about_us, name="about_us"),
    path("purchase_guide/", purchase_guide, name="purchase_guide"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),
]

UNIQUE_KNOWLEDGE_BD/templates/DEMO.html
My Code is:
"
{% for c in categories %}
            <section class="pb-5 section-padding">
                <div class="container">
                    <div class="section-title style-2 wow animate__animated animate__fadeIn">
                        <h3>{{ c.title }}</h3>
                        <ul class="nav nav-tabs links" id="myTab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <a href="{% url 'core:category-product-list' c.cid %}" class="nav-link active">
                                    সকল {{ c.title }} দেখুন
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!--End nav-tabs-->

                    <div class="row">
                        <div class="col-lg-3 d-none d-lg-flex wow animate__animated animate__fadeIn">
                            <div>

                                <a href="{% url 'core:category-product-list' c.cid %}"><img class="rounded-3 "
                                                                                            src="{{ c.image.url }}"
                                                                                            alt=""/></a>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-12 wow animate__animated animate__fadeIn" data-wow-delay=".4s">
                            <div class="tab-content" id="myTabContent-1">

                                <div class="tab-pane fade show active" id="tab-one-1" role="tabpanel"
                                     aria-labelledby="tab-one-1">
                                    <div class="carausel-4-columns-cover arrow-center position-relative">
                                        <div class="slider-arrow slider-arrow-2 carausel-4-columns-arrow"
                                             id="carausel-4-columns-arrows"></div>
                                        <div class="d-flex carausel-4-columns carausel-arrow-center">

                                            {% for p in products %}
                                            <div class="col-lg-1-4 col-md-3 col-12 col-sm-6">
                                                <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn"
                                                     data-wow-delay=".1s">
                                                    <div class="product-img-action-wrap ">
                                                        <div class="product-img product-img-zoom">
                                                            <a href="{% url 'core:product-detail' p.pid %}">
                                                                <img class="default-img" src="{{ p.image.url }}"
                                                                     alt=""/>
                                                                <img class="hover-img" src="{{ p.image.url }}" alt=""/>
                                                            </a>
                                                        </div>
                                                        <div class="product-action-1">
                                                            <a aria-label="Quick view" class="action-btn"
                                                               href="{% url 'core:product-detail' p.pid %}"><i
                                                                    class="fi-rs-eye"></i></a>
                                                            <a aria-label="Add To Wishlist"
                                                               class="action-btn small hover-up"
                                                               href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                                                            <a aria-label="Compare" class="action-btn small hover-up"
                                                               href="shop-compare.html"><i
                                                                    class="fi-rs-shuffle"></i></a>
                                                        </div>
                                                        <div class="product-badges product-badges-position product-badges-mrg">
                                                            <span class="hot">{{ p.get_percentage | floatformat:0 }}% Off</span>
                                                        </div>
                                                    </div>
                                                    <div class="product-content-wrap">
                                                        <div class="product-category">
                                                            <a href="{% url 'core:category-product-list' p.category.cid %}">{{ p.category.title }} </a>
                                                        </div>
                                                        <h2><a href="{% url 'core:product-detail' p.pid %}">{{ p.title }} </a>
                                                        </h2>
                                                        <div class="product-rate d-inline-block">
                                                            <div class="product-rating" style="width: 80%"></div>
                                                        </div>
                                                        <div>
                                                    <span class="font-small text-muted">প্রকানী: <a
                                                            href="{% url 'core:vendor-detail' p.vendor.vid %}">{{ p.vendor.title }} </a></span>
                                                        </div>
                                                        <div class="mt-2 product-price">
                                                            <span>৳ {{p.price}} </span>
                                                            <span class="old-price">৳ {{ p.old_price }}</span>
                                                        </div>
                                                        <div class="product-card-bottom">
                                                            <div class="add-cart">
                                                                <input type="hidden" value="1" id="product-quantity-1"
                                                                       class="product-quantity-{{p.id}}">
                                                                <input type="hidden" class="product-pid-{{p.id}}"
                                                                       value="{{p.pid}}">
                                                                <input type="hidden" class="product-image-{{p.id}}"
                                                                       value="{{p.image.url}}">
                                                                <input type="hidden" class="product-id-{{p.id}}"
                                                                       value="{{ p.id }}">
                                                                <input type="hidden" class="product-title-{{p.id}}"
                                                                       value="{{ p.title }}">

                                                                <div class="d-flex">
                                                                    <button class="add add-to-cart-btn b-none"
                                                                            style="border: none;"
                                                                            id="add-to-cart-btn-1"
                                                                            data-index="{{ p.id }}"><i
                                                                            class="mr-5 fi-rs-shopping-cart"></i>Add
                                                                    </button>
                                                                    <button class="add add-to-wishlist"
                                                                            style="border: none; background: none;"
                                                                            data-product-item="{{ p.id }}"><i
                                                                            class="fi-rs-heart"
                                                                            style="fill: aqua;"></i>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <a href="{% url 'core:product-detail' p.pid %}"
                                                           class="mt-3 btn w-100 hover-up"><i
                                                                class="mr-5 fi-rs-shopping-cart"></i>এখনই কিনুন</a>
                                                    </div>
                                                </div>
                                            </div>
                                            {% endfor %}
                                            <!--End product Wrap-->
                                        </div>
                                    </div>
                                </div>
                                <!--End tab-pane-->
                            </div>
                            <!--End tab-content-->
                        </div>
                        <!--End Col-lg-9-->
                    </div>
                </div>
            </section>
            {% endfor %}
"
How to show category-wise Product?