UNIQUE_KNOWLEDGE_BD/UNIQUE_KNOWLEDGE_BD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UNIQUE_KNOWLEDGE_BD/core/urls.py
from django import views
from django.urls import path, include
from core.views import (create_checkout_session, save_checkout_info, add_to_cart, add_to_wishlist, ajax_add_review,
                        ajax_contact_form, cart_view, category_list_view, category_product_list__view, checkout,
                        customer_dashboard, delete_item_from_cart, filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, product_detail_view, product_list_view, remove_wishlist, search_view, tag_list, update_cart, vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, purchase_guide, privacy_policy, terms_of_service)

app_name = "core"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list__view, name="category-product-list"),
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),
    path("save_checkout_info/", save_checkout_info, name="save_checkout_info"),
    path("checkout/<oid>/", checkout, name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-address/", make_address_default, name="make-default-address"),
    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),
    path("about_us/", about_us, name="about_us"),
    path("purchase_guide/", purchase_guide, name="purchase_guide"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),
]

UNIQUE_KNOWLEDGE_BD/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path("profile/update/", views.profile_update, name="profile-update"),
]

UNIQUE_KNOWLEDGE_BD/userauths/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.db.models.signals import post_save


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", null=True, blank=True)
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True) 
    address = models.CharField(max_length=200, null=True, blank=True) 
    country = models.CharField(max_length=200, null=True, blank=True) 
    verified = models.BooleanField(default=False, null=True, blank=True)
    
    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"


class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200) 
    subject = models.CharField(max_length=200) 
    message = models.TextField()

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self):
        return self.full_name

    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

 
post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)    

UNIQUE_KNOWLEDGE_BD/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"ইউজার নেম"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"ই-মেইল"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"পাসওয়ার্ড"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"কনফার্ম পাসওয়ার্ড"}))

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"পুরা নাম"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"বায়ো"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"ফোন"}))

    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

UNIQUE_KNOWLEDGE_BD/userauths/views.py
from django.shortcuts import redirect, render
from userauths.forms import UserRegisterForm, ProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import Profile, User


# User = settings.AUTH_USER_MODEL

def register_view(request):
    
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, You account was created successfully.")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            login(request, new_user)

            next_url = request.GET.get("next", 'core:index')
            return redirect(next_url)
    else:
        form = UserRegisterForm()


    context = {
        'form': form,
    }
    return render(request, "userauths/sign-up.html", context)


def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")
    
    if request.method == "POST":
        email = request.POST.get("email") # peanuts@gmail.com
        password = request.POST.get("password") # getmepeanuts

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")
                next_url = request.GET.get("next", 'core:index')
                return redirect(next_url)
            else:
                messages.warning(request, "User Does Not Exist, create an account.")
    
        except:
            messages.warning(request, f"User with {email} does not exist")
        

    
    return render(request, "userauths/sign-in.html")

        

def logout_view(request):

    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:sign-in")


def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, "Profile Updated Successfully.")
            return redirect("core:dashboard")
    else:
        form = ProfileForm(instance=profile)

    context = {
        "form": form,
        "profile": profile,
    }

    return render(request, "userauths/profile-edit.html", context)

UNIQUE_KNOWLEDGE_BD/templates/userauths/profile-edit.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>হোম</a>
                    <span></span> পেজ <span></span> মাই একাউন্ট
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 m-auto">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="dashboard-menu">
                                    <ul class="nav flex-column" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="profile-tab" data-bs-toggle="tab"
                                               href="#profile" role="tab" aria-controls="profile"
                                               aria-selected="false"><i class="fi-rs-user mr-10"></i>প্রফাইল</a>
                                        </li>
                                        
                                        <li class="nav-item">
                                            <a class="nav-link" href="page-login.html"><i
                                                    class="fi-rs-sign-out mr-10"></i>লগআউট</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="tab-content account dashboard-content pl-50">
                                    <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="card">
                                            <div class="card-header border-bottom">
                                                <h3 class="mb-0">আপডেট প্রফাইল</h3>
                                            </div>
                                            {% if form.errors %}
                                            <div class="alert-danger alert">
                                                <strong>{{ form.errors }}</strong>
                                            </div>
                                            {% endif %}
                                            <div class="card-body mb-2" style="display: flex; align-items: center; gap: 10px;">
                                                <div>
                                                    {% if profile.image %}
                                                    <span><img src="{{ profile.image.url }}" style="width: 150px; object-fit: cover; border-radius:50%; height:150px;" alt=""></span>
                                                    {% else %}
                                                    <span><img src="https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg" style="width: 150px; object-fit: cover; border-radius:50%; height:150px;" alt=""></span>
                                                    {% endif %}
                                                </div>
                                                    <div>
                                                        <form action="" method="POST" enctype="multipart/form-data"> 
                                                            {% csrf_token %}
                                                            <div class="mb-3">
                                                                {{form.full_name}}
                                                            </div>
                                                            <div class="mb-3">
                                                                {{form.bio}}
                                                            </div>
                                                            <div class="mb-3">
                                                                {{form.phone}}
                                                            </div>
                                                            <div class="mb-3">
                                                                {{form.image}}
                                                            </div>
                                                            <button class="bxtn btn-succees" type="submit">সংরক্ষণ করুন
                                                            </button>
                                                        </form>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>



{% endblock content %}

UNIQUE_KNOWLEDGE_BD/templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>হোম</a>
                    <span></span> পেজ <span></span> মাই একাউন্ট
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">লগইন</h1>
                                            <p class="mb-30">নতুন একাউন্ট তৈরি করতে
                                                <a href="{% url 'userauths:sign-up' %}">এখানে ক্লিক করুন</a>
                                            </p>
                                        </div>
                                        <form method="POST"> 
                                            {% csrf_token %}

                                            <div class="form-group">
                                                <input type="text" required name="email"
                                                       placeholder="ইউজার নেম অথবা ই-মেইল *" />
                                            </div>
                                            <div class="form-group">
                                                <input required type="password" name="password" placeholder="পাসওয়ার্ড *" />
                                            </div>

                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox1"><span>
                                                            মনে রাখুন</span></label>
                                                    </div>
                                                </div>
                                                <p class="mb-30">পাসওয়ার্ড ভুলে গেলে
                                                    <a href="#">এখানে ক্লিক করুন</a>
                                                </p>

                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">লগইন</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}

UNIQUE_KNOWLEDGE_BD/templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>হোম</a>
                    <span></span> পেজ <span></span> মাই একাউন্ট
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">

                                        {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}

                                        <div class="heading_s1">
                                            <h1 class="mb-5">একাউন্ট তৈরী করুন</h1>
                                            <p class="mb-30">পূর্বে একাউন্ট থাকলে লগইন করতে
                                                <a href="{% url 'userauths:sign-in' %}">এখানে ক্লিক করুন</a>
                                            </p>
                                        </div>
                                        <form method="post" method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                {{form.username}}
                                            </div>
                                            <div class="form-group">
                                                {{form.email}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password1}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password2}}
                                            </div>

                                            <div class="form-group mb-30">
                                                <button type="submit"
                                                        class="btn btn-fill-out btn-block hover-up font-weight-bold"
                                                        name="login">সাবমিট করুন</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}